### ISSUE TITLE
set'теры здесь логически не нужны

### ISSUE THREAD

**Issue by coursar** [sgv1995/ozon#3]
https://github.com/sgv1995/ozon/blob/e4f12d74f54fcfd8e33b3d4a7d8c26421ac13158/src/main/java/ru/itpark/Basket.java#L14-L16

**Comment by coursar** [comment]
Причём на все поля

**Comment by sgv1995** [comment]
Добавил изменения на все issue вместе, но закрылось только issue #2

**Comment by coursar** [comment]
надо писать fixes #2, fixes #3, fixes #4
