### ISSUE TITLE
Разве цена со скидкой не вычисляется на базе цены и скидки?

### ISSUE THREAD

**Issue by coursar** [sgv1995/ozon#4]
https://github.com/sgv1995/ozon/blob/e4f12d74f54fcfd8e33b3d4a7d8c26421ac13158/src/main/java/ru/itpark/Product.java#L7-L9

**Comment by sgv1995** [comment]
Добавил изменения на все issue вместе, но закрылось только issue #2

**Comment by coursar** [comment]
Так у вас осталось так же три поля, что исправили?

**Comment by sgv1995** [comment]
В классе Product теперь отсутствует discountPrice; По истории изменений это видно во вкладке <>code. Здесь по ссылке не правильно отображается почему-то

**Comment by sgv1995** [comment]
Совсем не то загрузилось

**Comment by sgv1995** [comment]
package ru.itpark;

public class Product {
    private int id;
    private String name;
    private String description;
    private int fullPrice;
    private int discountPercentage;
    private int rating;
    private String imageUrl;
    private boolean available;


    public Product(int id, String name, String description, int fullPrice, int discountPercentage, int rating, String imageUrl, boolean available) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.fullPrice = fullPrice;
        this.discountPercentage = discountPercentage;
        this.rating = rating;
        this.imageUrl = imageUrl;
        this.available = available;
    }

    public int getFullPrice() {
        return fullPrice;
    }
    public int getDiscountPercentage() {
        return discountPercentage;
    }
    public boolean getAvailable() { return available; }
    public void setAvailable(boolean available) { this.available = available; }
}

**Comment by sgv1995** [comment]
В таком виде Product должен был быть сразу. Здесь уже видно, что поля  private int discountPrice; нет. И цена со скидкой считается в другом классе автоматически.
